"use client";

import {FormEvent,useMemo,useState} from "react";
import ExplorerIcon from "./ExplorerIcon";
import useExplorerCollection from "../hooks/useExplorerCollection";
import {MODULE_META} from "../lib/explorer-data.mjs";
import type {ExplorerItem,ExplorerModule} from "../lib/explorer-types";

type Account={display_name:string;age:number;created_at?:string};
type NavigationView="planet"|"works"|"timeline"|"report";
type WorkModule=Exclude<ExplorerModule,"registration">;
const CORE_URL="http://localhost:8020";
const moduleOrder:WorkModule[]=["story","deep_sea","career","chat"];
const iconByModule:Record<WorkModule,"book"|"waves"|"map"|"journal">={story:"book",deep_sea:"waves",career:"map",chat:"journal"};
const moduleNames:Record<WorkModule,string>={story:"故事共创",deep_sea:"深海基地重建",career:"职业模拟器",chat:"聊天观察"};

function speak(text:string){if(!("speechSynthesis" in window))return;window.speechSynthesis.cancel();const voice=new SpeechSynthesisUtterance(text);voice.lang="zh-CN";voice.rate=.82;voice.pitch=1.06;window.speechSynthesis.speak(voice);}
function formatDate(value:string){const date=new Date(value);if(Number.isNaN(date.valueOf())||date.valueOf()===0)return "最近一次探索";return new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric"}).format(date);}

export default function WorksPage({account,onNavigate,perspective="student"}:{account:Account;onNavigate:(view:NavigationView)=>void;perspective?:"student"|"adult"}){
  const {data,loading,error,retry,refresh}=useExplorerCollection(account);
  const [section,setSection]=useState<WorkModule|null>(null),[selected,setSelected]=useState<ExplorerItem|null>(null),[largeText,setLargeText]=useState(false);
  const [comment,setComment]=useState(""),[commentError,setCommentError]=useState(""),[submitting,setSubmitting]=useState(false);
  const [manualOpen,setManualOpen]=useState(false),[manualError,setManualError]=useState(""),[manualLoading,setManualLoading]=useState(false);
  const grouped=useMemo(()=>Object.fromEntries(moduleOrder.map(key=>[key,data?.works.filter(item=>item.module===key)??[]])) as Record<WorkModule,ExplorerItem[]>,[data]);
  if(loading||!data)return <section className="personal-loading" aria-live="polite"><span className="loading-star"><ExplorerIcon name="spark" size={38}/></span><h1>正在整理全部作品…</h1><p>四座大陆正在把完成成果送回作品册。</p></section>;
  const adult=perspective==="adult";
  const openSection=(key:WorkModule)=>{setSection(key);setSelected(null);window.scrollTo({top:0,behavior:"smooth"});};
  async function submitComment(event:FormEvent){event.preventDefault();if(!selected||!comment.trim())return;setSubmitting(true);setCommentError("");try{const response=await fetch(`${CORE_URL}/api/explorer/comments`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({work_id:selected.id,body:comment})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload.detail==="string"?payload.detail:"点评没有保存成功");const item=payload.comment;setSelected({...selected,comments:[...selected.comments,{id:item.id,body:item.body,authorName:item.author_name,authorKind:item.author_kind,createdAt:item.created_at}]});setComment("");refresh();}catch(cause){setCommentError(cause instanceof Error?cause.message:"点评没有保存成功");}finally{setSubmitting(false);}}
  async function submitManualWork(event:FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget,form=new FormData(formElement);setManualLoading(true);setManualError("");try{const response=await fetch(`${CORE_URL}/api/explorer/works`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({module:form.get("module"),title:form.get("title"),description:form.get("description")})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload.detail==="string"?payload.detail:"作品没有添加成功");formElement.reset();setManualOpen(false);refresh();}catch(cause){setManualError(cause instanceof Error?cause.message:"作品没有添加成功");}finally{setManualLoading(false);}}
  async function deleteManualWork(){if(!selected||selected.kind!=="manual_work"||!window.confirm(`确定删除“${selected.title}”吗？`))return;const response=await fetch(`${CORE_URL}/api/explorer/works/${encodeURIComponent(selected.id)}`,{method:"DELETE",credentials:"include"});if(response.ok){setSelected(null);refresh();}else{const payload=await response.json().catch(()=>({}));setCommentError(typeof payload.detail==="string"?payload.detail:"作品没有删除成功");}}
  if(selected)return <section className={`works-view works-detail tone-${selected.tone}`}><div className="works-sky" aria-hidden="true"/><header className="personal-page-header"><button className="paper-action" onClick={()=>setSelected(null)}><ExplorerIcon name="arrow"/>返回{adult?"作品展柜":"作品列表"}</button><div><span className="header-icon"><ExplorerIcon name={iconByModule[selected.module as WorkModule]} size={27}/></span><h1>{selected.title}</h1><p>{selected.island} · {formatDate(selected.occurredAt)} {selected.isHighlight&&"· 高光作品"}</p></div><button className="listen-action" onClick={()=>speak(`${selected.title}。${selected.detail}。${selected.quote}`)}><ExplorerIcon name="headphones"/>听一听</button></header>
    <main className={`work-reader ${largeText?"is-large":""}`}><div className="reader-scene">{selected.snapshotUrl?<img src={selected.snapshotUrl} alt={`${selected.title}完成画面`}/>:<img src={selected.scene} alt={`${selected.collection}作品贴纸`}/>}<span>{selected.status}</span></div><article><div className="reader-toolbar"><button onClick={()=>setLargeText(v=>!v)}>字 {largeText?"小一点":"大一点"}</button><button onClick={()=>speak(`${selected.title}。${selected.detail}`)}><ExplorerIcon name="headphones" size={17}/>朗读这一页</button></div><p className="reader-date">{formatDate(selected.occurredAt)} · {data.worksAreDemo?"示例作品":"真实完成作品"}</p><h2>{selected.title}</h2><p className="reader-body">{selected.detail}</p>{selected.quote&&<blockquote>“{selected.quote.replace(/[“”]/g,"")}”</blockquote>}<div className="highlight-metric"><span>{selected.metricLabel}</span><strong>{selected.metricValue}</strong></div>{selected.isHighlight&&<div className="reader-note"><ExplorerIcon name="spark"/><p><b>为什么它会成为高光</b><span>{selected.summary}</span></p></div>}
      <section className="work-comments" aria-label="家长和老师点评"><h3>温暖点评 <small>{selected.comments.length} 条</small></h3>{selected.comments.length?<div className="comment-list">{selected.comments.map(item=><article key={item.id}><b>{item.authorName}<small>家长 / 老师</small></b><p>{item.body}</p><time>{formatDate(item.createdAt)}</time></article>)}</div>:<p className="comments-empty">还没有点评，完成作品本身就值得好好收藏。</p>}{adult&&!data.worksAreDemo&&<form onSubmit={submitComment}><label htmlFor="work-comment">写下具体、鼓励性的观察</label><textarea id="work-comment" value={comment} onChange={e=>setComment(e.target.value)} maxLength={300} required placeholder="例如：我注意到你遇到困难后换了一种方法，这份坚持很珍贵。"/><div><span>{comment.length}/300</span><button disabled={submitting||!comment.trim()}>{submitting?"正在保存…":"发表点评"}</button></div>{commentError&&<p className="login-error">{commentError}</p>}</form>}</section>
      <div className="reader-actions"><button className="gold-button" onClick={()=>onNavigate("timeline")}><ExplorerIcon name="compass"/>{adult?"看看成长足迹":"回到探索星球"}</button><button className="plain-button" onClick={()=>setSelected(null)}>继续看作品</button>{!adult&&selected.kind==="manual_work"&&<button className="delete-work-button" onClick={deleteManualWork}>删除这件作品</button>}</div></article></main></section>;
  if(section){const meta=MODULE_META[section],items=grouped[section];return <section className={`works-view works-collection tone-${meta.tone}`}><div className="works-sky" aria-hidden="true"/><header className="personal-page-header"><button className="paper-action" onClick={()=>setSection(null)}><ExplorerIcon name="arrow"/>回到作品总览</button><div><span className="header-icon"><ExplorerIcon name={iconByModule[section]} size={27}/></span><h1>{moduleNames[section]}</h1><p>共收藏 {items.length} 件完成作品，高光作品会显示星标。</p></div><strong>{items.length} 件<small>全部作品</small></strong></header><nav className="collection-tabs" aria-label="作品分类">{moduleOrder.map(key=><button key={key} className={key===section?"active":""} onClick={()=>openSection(key)}><ExplorerIcon name={iconByModule[key]}/><span>{moduleNames[key]}</span></button>)}</nav><main className="collection-stage"><div className="collection-art"><img src={meta.scene} alt=""/><p><ExplorerIcon name="spark"/>完成模块后会自动加入，无需手动上传。</p></div><div className="work-list">{items.length?items.map((item,index)=><button className="work-ticket" key={item.id} onClick={()=>setSelected(item)}><span className="ticket-number">{item.isHighlight?"★":String(index+1).padStart(2,"0")}</span><span><small>{formatDate(item.occurredAt)} · {item.status}</small><b>{item.title}</b><p>{item.summary}</p><em>{item.metricLabel} · {item.metricValue}{item.comments.length?` · ${item.comments.length} 条点评`:""}</em></span><i><ExplorerIcon name="arrow"/></i></button>):<div className="collection-empty"><ExplorerIcon name="spark" size={34}/><h2>这里正在等第一件作品</h2><p>完成一次{moduleNames[section]}，成果会自动来到这里。</p></div>}</div></main></section>}
  return <section className="works-view works-home"><div className="works-sky" aria-hidden="true"/><header className="works-welcome"><button className="back-to-planet" onClick={()=>onNavigate(adult?"report":"planet")}><ExplorerIcon name="compass"/>{adult?"回天赋报告":"回探索星球"}</button><div><h1>{adult?`${data.account.displayName}的作品展柜`:"这些作品来源于四座大陆"}</h1></div>{adult?<button className="listen-action" onClick={()=>speak(`这里收藏了${data.account.displayName}的全部作品。`)}><ExplorerIcon name="headphones"/>听一听</button>:<button className="add-work-button" onClick={()=>{setManualError("");setManualOpen(true)}}>＋ 添加作品</button>}</header><div className={`data-notice ${error?"is-error":""}`} role="status"><ExplorerIcon name="spark"/><span>{data.worksNotice}</span>{error&&<button onClick={retry}>再试一次</button>}</div>
    <main className="storybook-book"><div className="treasure-stickers">{moduleOrder.map((key,index)=>{const meta=MODULE_META[key],highlight=grouped[key].find(item=>item.isHighlight);return <button key={key} className={`treasure-sticker sticker-${index}`} onClick={()=>highlight?setSelected(highlight):openSection(key)}><span className="sticker-picture"><img src={meta.scene} alt=""/><i>{index+1}</i></span><span className="sticker-caption"><i><ExplorerIcon name={iconByModule[key]}/></i><span><b>{moduleNames[key]}</b><small>{highlight?.title??grouped[key][0]?.title??"等待第一件作品"}</small></span><ExplorerIcon name="arrow"/></span></button>})}</div><p className="book-guide"><ExplorerIcon name="spark"/>共有 {data.works.length} 件作品</p></main>
    <section className="all-works-shelf"><header><h2>全部作品</h2><span>探索完成或自己添加后都会出现在这里</span></header><div>{moduleOrder.map(key=><button key={key} onClick={()=>openSection(key)}><ExplorerIcon name={iconByModule[key]} size={28}/><b>{moduleNames[key]}</b><span>{grouped[key].length} 件</span><small>{grouped[key][0]?.title??"等待第一件作品"}</small></button>)}</div></section>
    {!adult&&manualOpen&&<div className="work-dialog-backdrop"><section className="work-dialog" role="dialog" aria-modal="true" aria-labelledby="add-work-title"><header><div><h2 id="add-work-title">添加我的作品</h2><p>选择作品来自哪座大陆，再写下它的名字和内容。</p></div><button type="button" aria-label="关闭" onClick={()=>setManualOpen(false)}>×</button></header><form onSubmit={submitManualWork}><label>所属大陆<select name="module" defaultValue="story"><option value="story">想象之洲 · 故事共创</option><option value="deep_sea">创造之洲 · 深海基地重建</option><option value="career">未来之洲 · 职业模拟器</option><option value="chat">倾听之洲 · 聊天观察</option></select></label><label>作品名称<input name="title" required maxLength={60} placeholder="给作品起一个名字"/></label><label>作品内容或介绍<textarea name="description" maxLength={1000} placeholder="可以写下作品内容、创作过程或想说的话"/></label>{manualError&&<p className="login-error" role="alert">{manualError}</p>}<div><button type="button" onClick={()=>setManualOpen(false)}>取消</button><button className="save-work-button" disabled={manualLoading}>{manualLoading?"添加中…":"添加到作品册"}</button></div></form></section></div>}
  </section>;
}
