<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import BookCover from "./book/BookCover.vue";import BookSpread from "./book/BookSpread.vue";import BookPagination from "./book/BookPagination.vue";import BookPageContent from "./book/BookPageContent.vue";import TurningLeaf from "./book/TurningLeaf.vue";
import { familyAdvice, insights, reportMeta, teacherAdvice, type Evidence, type Talent } from "../data/mockReport";
import { generateReport, getEvidence, type CoreEvidence, type GeneratedReport } from "../api/core";
import { momentsForTalent } from "../data/liveMoments";
import { useBookFlip } from "../composables/useBookFlip";import "../styles/book.css";import "../styles/report-polish.css";
const props=defineProps<{talents:Talent[]}>();defineEmits<{back:[];childView:[]}>();
const opened=ref(false),opening=ref(false),rawEvidence=ref<Evidence>(),rawVisible=ref(false),highlightedId=ref<string>();
const liveReport=ref<GeneratedReport>(),liveEvents=ref<CoreEvidence[]>([]);
const {currentSpread,fromSpread,targetSpread,direction,flipping,goTo,next,prev}=useBookFlip(9);
const canonical=(key:string)=>key==="logical_mathematical"?"logical":key;
const sourceNames:Record<string,string>={story:"故事共创",deep_sea:"深海基地重建",chat:"聊天观察",career:"职业模拟器"};
const displayTalents=computed(()=>props.talents.map(talent=>{if(!liveEvents.value.length)return {...talent,evidence:[],moments:[]};const events=liveEvents.value.filter(event=>event.intelligence_candidates.map(canonical).includes(talent.key));return {...talent,evidence:events.map(event=>{const explanation=liveReport.value?.evidence_explanations?.find(item=>item.evidence_ref===event.id);return {id:event.id,behavior:event.behavior_summary,source:sourceNames[event.module]||"探索活动",continent:`${talent.continent} · ${sourceNames[event.module]||"探索活动"}`,time:event.occurred_at.replace("T"," ").slice(0,16),level:event.evidence_level,raw:"",logTitle:explanation?.title||"探索过程回顾",logSummary:explanation?.summary||event.behavior_summary,logDetails:explanation?.details||["这次活动已留下可回溯的行为记录，后续可以结合更多情境继续观察。"]} as Evidence}),moments:momentsForTalent(liveEvents.value,talent.key)}}));
const reportInsights=computed(()=>liveReport.value?liveReport.value.cross_insights.map(item=>item.text):insights.map(item=>item.replace(/\[E\d+\]/g,"")));
const advice=(value:string|string[])=>Array.isArray(value)?value:[value];
const reportFamily=computed(()=>liveReport.value?advice(liveReport.value.recommendations.family):familyAdvice),reportTeacher=computed(()=>liveReport.value?advice(liveReport.value.recommendations.teacher):teacherAdvice);
const richNames=computed(()=>displayTalents.value.filter(t=>t.evidence.filter(e=>e.level==="strong").length>=2).map(t=>t.adultName)),fewNames=computed(()=>displayTalents.value.filter(t=>t.evidence.length<2).map(t=>t.adultName));
const bookPageProps=computed(()=>({talents:displayTalents.value,insights:reportInsights.value,richNames:richNames.value,fewNames:fewNames.value,family:reportFamily.value,teacher:reportTeacher.value,liveReport:liveReport.value,highlightedId:highlightedId.value}));
let openingTimer:number|undefined,highlightTimer:number|undefined;
function openBook(){if(opening.value)return;opening.value=true;openingTimer=window.setTimeout(()=>{opened.value=true;opening.value=false},1280)}function closeBook(){opened.value=false;currentSpread.value=0}function previous(){if(currentSpread.value===0){closeBook();return}prev()}function forward(){if(currentSpread.value===8){ElMessage.info("已经是最后一页啦 ✦");return}next()}
function openRaw(evidence:Evidence){rawEvidence.value=evidence;rawVisible.value=true}function jumpEvidence(id:string){const index=displayTalents.value.findIndex(t=>t.evidence.some(e=>e.id===id));if(index<0)return;goTo(index+2);window.clearTimeout(highlightTimer);window.setTimeout(async()=>{highlightedId.value=id;await nextTick();document.getElementById(`evidence-${id}`)?.scrollIntoView({block:"center"});highlightTimer=window.setTimeout(()=>highlightedId.value=undefined,1200)},520)}
function exportPdf(){document.querySelector<HTMLButtonElement>(".report-footer .primary")?.click()}function onKeydown(event:KeyboardEvent){if(event.key==="ArrowLeft"){event.preventDefault();opened.value?previous():undefined}else if(event.key==="ArrowRight"){event.preventDefault();opened.value?forward():openBook()}}
onMounted(async()=>{window.addEventListener("keydown",onKeydown);const evidence=await getEvidence();if(evidence?.events.length){liveEvents.value=evidence.events;const report=await generateReport(evidence.account.display_name,evidence.events);if(report)liveReport.value=report}});onBeforeUnmount(()=>{window.removeEventListener("keydown",onKeydown);window.clearTimeout(openingTimer);window.clearTimeout(highlightTimer)});
</script>
<template><div class="magic-book-app"><header class="storybook-toolbar"><div class="storybook-toolbar-actions"><button class="ribbon-button" @click="$emit('back')"><img src="/assets/report-watercolor/report-planet-v1.webp" alt=""/>返回探索星球</button><button class="child-view-button" @click="$emit('childView')">切换孩子视角 →</button></div><div><small>AI BOLE · TALENT REPORT</small><b>天赋魔法书</b></div><div class="toolbar-end"><button class="paper-button" :disabled="!opened" @click="closeBook">回到封面</button></div></header><main class="magic-book-main"><BookCover v-if="!opened" :range="reportMeta.range" :opening="opening" @open="openBook"/><div v-else class="open-book-shell" :class="[`flip-${direction}`,{flipping}]"><BookSpread :number="currentSpread+1" :can-prev="true" :can-next="currentSpread<8" @prev="previous" @next="forward"><template #left><BookPageContent v-bind="bookPageProps" :spread-index="currentSpread" side="left" @open="openRaw" @evidence="jumpEvidence" @finish="closeBook"/></template><template #right><BookPageContent v-bind="bookPageProps" :spread-index="currentSpread" side="right" @open="openRaw" @evidence="jumpEvidence" @finish="closeBook"/></template></BookSpread><TurningLeaf v-if="flipping" :direction="direction"><template #front><BookPageContent v-bind="bookPageProps" :spread-index="fromSpread" :side="direction==='next'?'right':'left'"/></template><template #back><BookPageContent v-bind="bookPageProps" :spread-index="targetSpread" :side="direction==='next'?'left':'right'"/></template></TurningLeaf></div></main><footer class="storybook-footer"><span>{{opened?`第 ${currentSpread+1} / 9 跨页`:'封面 · 等待开启'}}</span><BookPagination v-if="opened" :current="currentSpread" @select="goTo"/><button class="envelope-button" @click="exportPdf"><img src="/assets/report-watercolor/report-story-v1.webp" alt=""/>导出 PDF</button></footer><el-dialog v-model="rawVisible" width="min(620px,92vw)" class="book-raw-dialog" title="这次探索发生了什么" align-center><template v-if="rawEvidence"><div class="book-raw-meta"><span>{{rawEvidence.source}}</span><time>{{rawEvidence.time}}</time><em>{{rawEvidence.level==='strong'?'较完整记录':'参考线索'}}</em></div><section class="human-log"><h3>{{rawEvidence.logTitle||'探索过程回顾'}}</h3><p>{{rawEvidence.logSummary||rawEvidence.behavior}}</p><ul><li v-for="detail in rawEvidence.logDetails" :key="detail">{{detail}}</li></ul></section><small>这段回顾由报告智能体根据活动过程整理，只描述当时发生的行为，不代表能力分数或排名。</small></template></el-dialog></div></template>
