const CORE_URL = import.meta.env.VITE_CORE_API_URL || "http://localhost:8020";
export type CoreAccount = { id:string; username:string; display_name:string; age?:number; created_at:string };
export type TalentEligibility = { key:string; name:string; eligible:boolean; strongCount:number; referenceCount:number; sourceModules:string[]; completedModules:string[]; recentEvidenceRecordId:string|null; recentEvidenceModuleId:string|null };
export type CoreEvidenceRecord = { id:string; sourceEventId:string; sessionId:string; moduleId:string; moduleVersion:string; eventType:string; occurredAt:string; evidenceLevel:"strong"|"reference"; constructs:string[]; reportDimensions:string[]; behaviorSummary:string; payload:Record<string,unknown>; sessionSummary?:Record<string,unknown>; artifactTitle?:string|null; artifactSummary?:string|null; previewResourceId?:string|null; previewUrl?:string|null };
export type ReportDimension = { key:string; name:string; status:string; evidence_refs:string[]; analysis:string; adult_observation:string; child_story:string };
export type EvidenceExplanation = { evidence_ref:string|null;title:string;summary:string;details:string[] };
export type ReflectionQuestion = {id:string;category?:string;key?:string;evidence_ref?:string;module?:string;evidence_brief?:string;lead:string;question:string;options:string[];allow_text:boolean;placeholder:string};
export type ReflectionQuestions = {question_version?:string;lead_note:string;global_questions:ReflectionQuestion[];dimension_questions:ReflectionQuestion[]};
export type ReflectionAnswer = {id:string;selected:string;text:string};
export type PersonalizedSuggestion = {consistency:{conclusion:string;text:string};family_suggestions:string[];teacher_suggestions:string[];transition_note:string};
export type GeneratedReport = { report_id?:string;generated_at:string; rule:string; dimensions:ReportDimension[]; cross_insights:{text:string;evidence_refs:string[]}[]; evidence_explanations:EvidenceExplanation[]; recommendations:{family:string|string[];teacher:string|string[]};questions?:ReflectionQuestions;feedback_completed?:boolean;personalized_recommendations?:Record<string,PersonalizedSuggestion> };
async function coreFetch<T>(path:string):Promise<T|null>{try{const response=await fetch(`${CORE_URL}${path}`,{credentials:"include"});if(!response.ok)return null;return await response.json() as T}catch{return null}}
export async function getAccount(){const payload=await coreFetch<{account:CoreAccount;selected_student?:CoreAccount|null}>("/api/account/me");return payload?{account:payload.selected_student||payload.account}:null}
export async function getTalentEligibility(){return coreFetch<{rule:string;talents:TalentEligibility[]}>("/api/v1/talents")}
export async function generateTalentStories(){try{const response=await fetch(`${CORE_URL}/api/v1/talent-stories`,{method:"POST",credentials:"include"});if(!response.ok)return null;return await response.json() as {generatedAt:string;generator:string;stories:{key:string;story:string;evidenceRefs:string[]}[]}}catch{return null}}
export async function getEvidenceRecords(){return coreFetch<{records:CoreEvidenceRecord[]}>("/api/v1/evidence-records?limit=500")}
// 报告页打开时基于当前证据重新生成快照。不能先返回 latest-published，
// 否则孩子完成一次新探索后仍会一直看到上一次的旧报告。
export async function generateReport():Promise<GeneratedReport|null>{try{const response=await fetch(`${CORE_URL}/api/v1/reports`,{method:"POST",credentials:"include"});if(!response.ok)return null;const payload=await response.json() as {id:string;report:GeneratedReport};return {...payload.report,report_id:payload.id}}catch{return null}}
export async function submitParentFeedback(reportId:string,dimensionKey:string,questions:ReflectionQuestion[],answers:ReflectionAnswer[]):Promise<{report:GeneratedReport;suggestion:PersonalizedSuggestion}>{const response=await fetch(`${CORE_URL}/api/v1/reports/${encodeURIComponent(reportId)}/parent-feedback`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({dimension_key:dimensionKey,questions,answers})});const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(typeof payload.detail==="string"?payload.detail:"专属建议暂时没有写好");return payload as {report:GeneratedReport;suggestion:PersonalizedSuggestion}}
