"use client";
import {useCallback,useEffect,useState} from "react";
import {createDemoCollection,normalizeCollectionResponse} from "../lib/explorer-data.mjs";
import type {ExplorerCollection} from "../lib/explorer-types";
import {CORE_API_URL} from "../config/modules";

const number=(value:any)=>Number(value)||0;
function collectionFromV1(account:{display_name:string;age:number;created_at?:string},artifacts:any[],summaries:any[]){return {account,works:artifacts.map(artifact=>({id:artifact.id,module:artifact.moduleId,kind:"highlight",title:artifact.title,summary:artifact.summary,detail:artifact.sourceResourceId?`资源编号：${artifact.sourceResourceId}`:artifact.summary,occurred_at:artifact.createdAt,status:"已收藏",metric_label:"作品记录",metric_value:artifact.type,usage_count:1})),milestones:summaries.map(summary=>({id:`v1-summary-${summary.moduleId}`,module:summary.moduleId,kind:"module_summary",title:`${summary.moduleId} 的完成小结`,summary:`共留下 ${summary.completedCount} 次探索记录。`,detail:`其中包含 ${summary.evidenceCount} 条证据${summary.artifactCount?` 和 ${summary.artifactCount} 件作品`:""}。`,occurred_at:summary.lastUsedAt,status:"模块已点亮",metric_label:"累计完成",metric_value:`${summary.completedCount} 次探索 · 累计 ${Math.max(0,Math.round(number(summary.activeSeconds)/60))} 分钟`,usage_count:summary.completedCount,first_used_at:summary.firstUsedAt,last_used_at:summary.lastUsedAt,duration_seconds:summary.activeSeconds||0,duration_coverage:1}))}}
async function readCollectionV1(account:{display_name:string;age:number;created_at?:string}){const [artifactsResponse,timelineResponse]=await Promise.all([fetch(`${CORE_API_URL}/api/v1/artifacts`,{credentials:"include"}),fetch(`${CORE_API_URL}/api/v1/timeline`,{credentials:"include"})]);if(!artifactsResponse.ok||!timelineResponse.ok)throw new Error("暂时没有连上星球记录");const [artifacts,timeline]=await Promise.all([artifactsResponse.json(),timelineResponse.json()]);return collectionFromV1(account,artifacts.artifacts||[],timeline.moduleSummaries||[])}
export default function useExplorerCollection(account:{display_name:string;age:number;created_at?:string}){const [data,setData]=useState<ExplorerCollection|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[attempt,setAttempt]=useState(0);const retry=useCallback(()=>{setLoading(true);setError("");setAttempt(value=>value+1)},[]);useEffect(()=>{const controller=new AbortController();readCollectionV1(account).then(payload=>setData(normalizeCollectionResponse(payload))).catch(cause=>{if(controller.signal.aborted)return;const fallback=createDemoCollection({displayName:account.display_name,age:account.age,createdAt:account.created_at});const notice="暂时没有连上真实记录，这里先展示清楚标注的示例。你可以继续浏览，稍后再试一次。";setData({...fallback,worksNotice:notice,timelineNotice:notice,notice});setError(cause instanceof Error?cause.message:"暂时没有连上星球记录")}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[account.display_name,account.age,account.created_at,attempt]);return {data,loading,error,retry}}
